<?php

namespace Tests\Unit;

use App\Models\Customer;
use PHPUnit\Framework\TestCase;

class CustomerTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->customer = new Customer([
            'first_name' => 'foo',
            'last_name' => 'bar',
        ]);
    }

    public function test_get_full_name_attribute_with_both_names()
    {
        $this->assertEquals('foo bar', $this->customer->full_name);
    }

    public function test_get_full_name_attribute_with_first_name_only()
    {
        $this->customer->last_name = '';
        $this->assertEquals('foo', $this->customer->full_name);
    }

    public function test_get_full_name_attribute_with_last_name_only()
    {
        $this->customer->first_name = '';
        $this->assertEquals('bar', $this->customer->full_name);
    }

    public function test_get_full_name_attribute_with_one_name_as_null()
    {
        $this->customer->last_name = null;
        $this->assertEquals('foo', $this->customer->full_name);
    }
}
